/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.core;

public class MgPlayShapes {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MgPlayShapes(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MgPlayShapes obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        touchvgJNI.delete_MgPlayShapes(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MgPlayShapes(String path, GiTransform xform) {
    this(touchvgJNI.new_MgPlayShapes(path, GiTransform.getCPtr(xform), xform), true);
  }

  public boolean loadFirstFile() {
    return touchvgJNI.MgPlayShapes_loadFirstFile(swigCPtr, this);
  }

  public int loadNextFile(int index) {
    return touchvgJNI.MgPlayShapes_loadNextFile(swigCPtr, this, index);
  }

  public void copyXform(GiTransform xform) {
    touchvgJNI.MgPlayShapes_copyXform(swigCPtr, this, GiTransform.getCPtr(xform), xform);
  }

  public MgShapeDoc pickFrontDoc() {
    long cPtr = touchvgJNI.MgPlayShapes_pickFrontDoc(swigCPtr, this);
    return (cPtr == 0) ? null : new MgShapeDoc(cPtr, false);
  }

  public MgShapes pickDynShapes() {
    long cPtr = touchvgJNI.MgPlayShapes_pickDynShapes(swigCPtr, this);
    return (cPtr == 0) ? null : new MgShapes(cPtr, false);
  }

  public final static int ADD = touchvgJNI.MgPlayShapes_ADD_get();
  public final static int EDIT = touchvgJNI.MgPlayShapes_EDIT_get();
  public final static int DEL = touchvgJNI.MgPlayShapes_DEL_get();
  public final static int STATIC_CHANGED = touchvgJNI.MgPlayShapes_STATIC_CHANGED_get();
  public final static int DYNAMIC_CHANGED = touchvgJNI.MgPlayShapes_DYNAMIC_CHANGED_get();
  public final static int FRAME_CHANGED = touchvgJNI.MgPlayShapes_FRAME_CHANGED_get();
  public final static int TICKMASK = touchvgJNI.MgPlayShapes_TICKMASK_get();

}
