/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package touchvg.core;

public class touchvgJNI {
  public final static native long new_TestOpenVGCanvas(int jarg1, int jarg2, int jarg3);
  public final static native void delete_TestOpenVGCanvas(long jarg1);
  public final static native void TestOpenVGCanvas_resize(long jarg1, TestOpenVGCanvas jarg1_, int jarg2, int jarg3);
  public final static native int TestOpenVGCanvas_getWidth(long jarg1, TestOpenVGCanvas jarg1_);
  public final static native int TestOpenVGCanvas_getHeight(long jarg1, TestOpenVGCanvas jarg1_);
  public final static native void TestOpenVGCanvas_prepareToDraw(long jarg1, TestOpenVGCanvas jarg1_, boolean jarg2, int jarg3);
  public final static native void TestOpenVGCanvas_draw__SWIG_0(long jarg1, TestOpenVGCanvas jarg1_, int jarg2, int jarg3, boolean jarg4);
  public final static native void TestOpenVGCanvas_draw__SWIG_1(long jarg1, TestOpenVGCanvas jarg1_, int jarg2, int jarg3);
  public final static native void TestOpenVGCanvas_dyndraw(long jarg1, TestOpenVGCanvas jarg1_, float jarg2, float jarg3);
}
